//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_Tilemaps_TilemapWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UnityEngine.Tilemaps.Tilemap), typeof(UnityEngine.GridLayout),"Tilemap");
		L.RegFunction("GetCellCenterLocal", GetCellCenterLocal);
		L.RegFunction("GetCellCenterWorld", GetCellCenterWorld);
		L.RegFunction("GetTile", GetTile);
		L.RegFunction("GetTilesBlock", GetTilesBlock);
		L.RegFunction("GetTilesBlockNonAlloc", GetTilesBlockNonAlloc);
		L.RegFunction("GetTilesRangeCount", GetTilesRangeCount);
		L.RegFunction("GetTilesRangeNonAlloc", GetTilesRangeNonAlloc);
		L.RegFunction("SetTile", SetTile);
		L.RegFunction("SetTiles", SetTiles);
		L.RegFunction("SetTilesBlock", SetTilesBlock);
		L.RegFunction("HasTile", HasTile);
		L.RegFunction("RefreshTile", RefreshTile);
		L.RegFunction("RefreshAllTiles", RefreshAllTiles);
		L.RegFunction("SwapTile", SwapTile);
		L.RegFunction("ContainsTile", ContainsTile);
		L.RegFunction("GetUsedTilesCount", GetUsedTilesCount);
		L.RegFunction("GetUsedSpritesCount", GetUsedSpritesCount);
		L.RegFunction("GetUsedTilesNonAlloc", GetUsedTilesNonAlloc);
		L.RegFunction("GetUsedSpritesNonAlloc", GetUsedSpritesNonAlloc);
		L.RegFunction("GetSprite", GetSprite);
		L.RegFunction("GetTransformMatrix", GetTransformMatrix);
		L.RegFunction("SetTransformMatrix", SetTransformMatrix);
		L.RegFunction("GetColor", GetColor);
		L.RegFunction("SetColor", SetColor);
		L.RegFunction("GetTileFlags", GetTileFlags);
		L.RegFunction("SetTileFlags", SetTileFlags);
		L.RegFunction("AddTileFlags", AddTileFlags);
		L.RegFunction("RemoveTileFlags", RemoveTileFlags);
		L.RegFunction("GetInstantiatedObject", GetInstantiatedObject);
		L.RegFunction("GetObjectToInstantiate", GetObjectToInstantiate);
		L.RegFunction("SetColliderType", SetColliderType);
		L.RegFunction("GetColliderType", GetColliderType);
		L.RegFunction("GetAnimationFrameCount", GetAnimationFrameCount);
		L.RegFunction("GetAnimationFrame", GetAnimationFrame);
		L.RegFunction("SetAnimationFrame", SetAnimationFrame);
		L.RegFunction("GetAnimationTime", GetAnimationTime);
		L.RegFunction("SetAnimationTime", SetAnimationTime);
		L.RegFunction("GetTileAnimationFlags", GetTileAnimationFlags);
		L.RegFunction("SetTileAnimationFlags", SetTileAnimationFlags);
		L.RegFunction("AddTileAnimationFlags", AddTileAnimationFlags);
		L.RegFunction("RemoveTileAnimationFlags", RemoveTileAnimationFlags);
		L.RegFunction("FloodFill", FloodFill);
		L.RegFunction("BoxFill", BoxFill);
		L.RegFunction("InsertCells", InsertCells);
		L.RegFunction("DeleteCells", DeleteCells);
		L.RegFunction("ClearAllTiles", ClearAllTiles);
		L.RegFunction("ResizeBounds", ResizeBounds);
		L.RegFunction("CompressBounds", CompressBounds);
		L.RegFunction("New", _CreateUnityEngine_Tilemaps_Tilemap);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("layoutGrid", get_layoutGrid, null);
		L.RegVar("cellBounds", get_cellBounds, null);
		L.RegVar("localBounds", get_localBounds, null);
		L.RegVar("animationFrameRate", get_animationFrameRate, set_animationFrameRate);
		L.RegVar("color", get_color, set_color);
		L.RegVar("origin", get_origin, set_origin);
		L.RegVar("size", get_size, set_size);
		L.RegVar("tileAnchor", get_tileAnchor, set_tileAnchor);
		L.RegVar("orientation", get_orientation, set_orientation);
		L.RegVar("orientationMatrix", get_orientationMatrix, set_orientationMatrix);
		L.RegVar("tilemapPositionsChanged", get_tilemapPositionsChanged, set_tilemapPositionsChanged);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateUnityEngine_Tilemaps_Tilemap(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				UnityEngine.Tilemaps.Tilemap obj = new UnityEngine.Tilemaps.Tilemap();
				ToLua.PushSealed(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: UnityEngine.Tilemaps.Tilemap.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetCellCenterLocal(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			UnityEngine.Vector3Int arg0 = ToLua.ToVector3Int(L, 2);
			UnityEngine.Vector3 o = obj.GetCellCenterLocal(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetCellCenterWorld(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			UnityEngine.Vector3Int arg0 = ToLua.ToVector3Int(L, 2);
			UnityEngine.Vector3 o = obj.GetCellCenterWorld(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetTile(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			UnityEngine.Vector3Int arg0 = ToLua.ToVector3Int(L, 2);
			UnityEngine.Tilemaps.TileBase o = obj.GetTile(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetTilesBlock(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			UnityEngine.BoundsInt arg0 = StackTraits<UnityEngine.BoundsInt>.Check(L, 2);
			UnityEngine.Tilemaps.TileBase[] o = obj.GetTilesBlock(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetTilesBlockNonAlloc(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			UnityEngine.BoundsInt arg0 = StackTraits<UnityEngine.BoundsInt>.Check(L, 2);
			UnityEngine.Tilemaps.TileBase[] arg1 = ToLua.CheckObjectArray<UnityEngine.Tilemaps.TileBase>(L, 3);
			int o = obj.GetTilesBlockNonAlloc(arg0, arg1);
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetTilesRangeCount(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			UnityEngine.Vector3Int arg0 = ToLua.ToVector3Int(L, 2);
			UnityEngine.Vector3Int arg1 = ToLua.ToVector3Int(L, 3);
			int o = obj.GetTilesRangeCount(arg0, arg1);
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetTilesRangeNonAlloc(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 5);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			UnityEngine.Vector3Int arg0 = ToLua.ToVector3Int(L, 2);
			UnityEngine.Vector3Int arg1 = ToLua.ToVector3Int(L, 3);
			UnityEngine.Vector3Int[] arg2 = ToLua.CheckStructArray<UnityEngine.Vector3Int>(L, 4);
			UnityEngine.Tilemaps.TileBase[] arg3 = ToLua.CheckObjectArray<UnityEngine.Tilemaps.TileBase>(L, 5);
			int o = obj.GetTilesRangeNonAlloc(arg0, arg1, arg2, arg3);
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetTile(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 3 && TypeChecker.CheckTypes<UnityEngine.Tilemaps.TileChangeData, bool>(L, 2))
			{
				UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
				UnityEngine.Tilemaps.TileChangeData arg0 = StackTraits<UnityEngine.Tilemaps.TileChangeData>.To(L, 2);
				bool arg1 = LuaDLL.lua_toboolean(L, 3);
				obj.SetTile(arg0, arg1);
				return 0;
			}
			else if (count == 3 && TypeChecker.CheckTypes<UnityEngine.Vector3Int, UnityEngine.Tilemaps.TileBase>(L, 2))
			{
				UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
				UnityEngine.Vector3Int arg0 = ToLua.ToVector3Int(L, 2);
				UnityEngine.Tilemaps.TileBase arg1 = (UnityEngine.Tilemaps.TileBase)ToLua.ToObject(L, 3);
				obj.SetTile(arg0, arg1);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: UnityEngine.Tilemaps.Tilemap.SetTile");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetTiles(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 3 && TypeChecker.CheckTypes<UnityEngine.Tilemaps.TileChangeData[], bool>(L, 2))
			{
				UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
				UnityEngine.Tilemaps.TileChangeData[] arg0 = ToLua.ToStructArray<UnityEngine.Tilemaps.TileChangeData>(L, 2);
				bool arg1 = LuaDLL.lua_toboolean(L, 3);
				obj.SetTiles(arg0, arg1);
				return 0;
			}
			else if (count == 3 && TypeChecker.CheckTypes<UnityEngine.Vector3Int[], UnityEngine.Tilemaps.TileBase[]>(L, 2))
			{
				UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
				UnityEngine.Vector3Int[] arg0 = ToLua.ToStructArray<UnityEngine.Vector3Int>(L, 2);
				UnityEngine.Tilemaps.TileBase[] arg1 = ToLua.ToObjectArray<UnityEngine.Tilemaps.TileBase>(L, 3);
				obj.SetTiles(arg0, arg1);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: UnityEngine.Tilemaps.Tilemap.SetTiles");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetTilesBlock(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			UnityEngine.BoundsInt arg0 = StackTraits<UnityEngine.BoundsInt>.Check(L, 2);
			UnityEngine.Tilemaps.TileBase[] arg1 = ToLua.CheckObjectArray<UnityEngine.Tilemaps.TileBase>(L, 3);
			obj.SetTilesBlock(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int HasTile(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			UnityEngine.Vector3Int arg0 = ToLua.ToVector3Int(L, 2);
			bool o = obj.HasTile(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RefreshTile(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			UnityEngine.Vector3Int arg0 = ToLua.ToVector3Int(L, 2);
			obj.RefreshTile(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RefreshAllTiles(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			obj.RefreshAllTiles();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SwapTile(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			UnityEngine.Tilemaps.TileBase arg0 = (UnityEngine.Tilemaps.TileBase)ToLua.CheckObject<UnityEngine.Tilemaps.TileBase>(L, 2);
			UnityEngine.Tilemaps.TileBase arg1 = (UnityEngine.Tilemaps.TileBase)ToLua.CheckObject<UnityEngine.Tilemaps.TileBase>(L, 3);
			obj.SwapTile(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ContainsTile(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			UnityEngine.Tilemaps.TileBase arg0 = (UnityEngine.Tilemaps.TileBase)ToLua.CheckObject<UnityEngine.Tilemaps.TileBase>(L, 2);
			bool o = obj.ContainsTile(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetUsedTilesCount(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			int o = obj.GetUsedTilesCount();
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetUsedSpritesCount(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			int o = obj.GetUsedSpritesCount();
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetUsedTilesNonAlloc(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			UnityEngine.Tilemaps.TileBase[] arg0 = ToLua.CheckObjectArray<UnityEngine.Tilemaps.TileBase>(L, 2);
			int o = obj.GetUsedTilesNonAlloc(arg0);
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetUsedSpritesNonAlloc(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			UnityEngine.Sprite[] arg0 = ToLua.CheckObjectArray<UnityEngine.Sprite>(L, 2);
			int o = obj.GetUsedSpritesNonAlloc(arg0);
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetSprite(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			UnityEngine.Vector3Int arg0 = ToLua.ToVector3Int(L, 2);
			UnityEngine.Sprite o = obj.GetSprite(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetTransformMatrix(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			UnityEngine.Vector3Int arg0 = ToLua.ToVector3Int(L, 2);
			UnityEngine.Matrix4x4 o = obj.GetTransformMatrix(arg0);
			ToLua.PushValue(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetTransformMatrix(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			UnityEngine.Vector3Int arg0 = ToLua.ToVector3Int(L, 2);
			UnityEngine.Matrix4x4 arg1 = StackTraits<UnityEngine.Matrix4x4>.Check(L, 3);
			obj.SetTransformMatrix(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetColor(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			UnityEngine.Vector3Int arg0 = ToLua.ToVector3Int(L, 2);
			UnityEngine.Color o = obj.GetColor(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetColor(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			UnityEngine.Vector3Int arg0 = ToLua.ToVector3Int(L, 2);
			UnityEngine.Color arg1 = ToLua.ToColor(L, 3);
			obj.SetColor(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetTileFlags(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			UnityEngine.Vector3Int arg0 = ToLua.ToVector3Int(L, 2);
			UnityEngine.Tilemaps.TileFlags o = obj.GetTileFlags(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetTileFlags(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			UnityEngine.Vector3Int arg0 = ToLua.ToVector3Int(L, 2);
			UnityEngine.Tilemaps.TileFlags arg1 = (UnityEngine.Tilemaps.TileFlags)ToLua.CheckObject(L, 3, typeof(UnityEngine.Tilemaps.TileFlags));
			obj.SetTileFlags(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddTileFlags(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			UnityEngine.Vector3Int arg0 = ToLua.ToVector3Int(L, 2);
			UnityEngine.Tilemaps.TileFlags arg1 = (UnityEngine.Tilemaps.TileFlags)ToLua.CheckObject(L, 3, typeof(UnityEngine.Tilemaps.TileFlags));
			obj.AddTileFlags(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RemoveTileFlags(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			UnityEngine.Vector3Int arg0 = ToLua.ToVector3Int(L, 2);
			UnityEngine.Tilemaps.TileFlags arg1 = (UnityEngine.Tilemaps.TileFlags)ToLua.CheckObject(L, 3, typeof(UnityEngine.Tilemaps.TileFlags));
			obj.RemoveTileFlags(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetInstantiatedObject(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			UnityEngine.Vector3Int arg0 = ToLua.ToVector3Int(L, 2);
			UnityEngine.GameObject o = obj.GetInstantiatedObject(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetObjectToInstantiate(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			UnityEngine.Vector3Int arg0 = ToLua.ToVector3Int(L, 2);
			UnityEngine.GameObject o = obj.GetObjectToInstantiate(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetColliderType(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			UnityEngine.Vector3Int arg0 = ToLua.ToVector3Int(L, 2);
			UnityEngine.Tilemaps.Tile.ColliderType arg1 = (UnityEngine.Tilemaps.Tile.ColliderType)ToLua.CheckObject(L, 3, typeof(UnityEngine.Tilemaps.Tile.ColliderType));
			obj.SetColliderType(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetColliderType(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			UnityEngine.Vector3Int arg0 = ToLua.ToVector3Int(L, 2);
			UnityEngine.Tilemaps.Tile.ColliderType o = obj.GetColliderType(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetAnimationFrameCount(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			UnityEngine.Vector3Int arg0 = ToLua.ToVector3Int(L, 2);
			int o = obj.GetAnimationFrameCount(arg0);
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetAnimationFrame(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			UnityEngine.Vector3Int arg0 = ToLua.ToVector3Int(L, 2);
			int o = obj.GetAnimationFrame(arg0);
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetAnimationFrame(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			UnityEngine.Vector3Int arg0 = ToLua.ToVector3Int(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			obj.SetAnimationFrame(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetAnimationTime(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			UnityEngine.Vector3Int arg0 = ToLua.ToVector3Int(L, 2);
			float o = obj.GetAnimationTime(arg0);
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetAnimationTime(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			UnityEngine.Vector3Int arg0 = ToLua.ToVector3Int(L, 2);
			float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
			obj.SetAnimationTime(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetTileAnimationFlags(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			UnityEngine.Vector3Int arg0 = ToLua.ToVector3Int(L, 2);
			UnityEngine.Tilemaps.TileAnimationFlags o = obj.GetTileAnimationFlags(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetTileAnimationFlags(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			UnityEngine.Vector3Int arg0 = ToLua.ToVector3Int(L, 2);
			UnityEngine.Tilemaps.TileAnimationFlags arg1 = (UnityEngine.Tilemaps.TileAnimationFlags)ToLua.CheckObject(L, 3, typeof(UnityEngine.Tilemaps.TileAnimationFlags));
			obj.SetTileAnimationFlags(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddTileAnimationFlags(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			UnityEngine.Vector3Int arg0 = ToLua.ToVector3Int(L, 2);
			UnityEngine.Tilemaps.TileAnimationFlags arg1 = (UnityEngine.Tilemaps.TileAnimationFlags)ToLua.CheckObject(L, 3, typeof(UnityEngine.Tilemaps.TileAnimationFlags));
			obj.AddTileAnimationFlags(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RemoveTileAnimationFlags(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			UnityEngine.Vector3Int arg0 = ToLua.ToVector3Int(L, 2);
			UnityEngine.Tilemaps.TileAnimationFlags arg1 = (UnityEngine.Tilemaps.TileAnimationFlags)ToLua.CheckObject(L, 3, typeof(UnityEngine.Tilemaps.TileAnimationFlags));
			obj.RemoveTileAnimationFlags(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FloodFill(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			UnityEngine.Vector3Int arg0 = ToLua.ToVector3Int(L, 2);
			UnityEngine.Tilemaps.TileBase arg1 = (UnityEngine.Tilemaps.TileBase)ToLua.CheckObject<UnityEngine.Tilemaps.TileBase>(L, 3);
			obj.FloodFill(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int BoxFill(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 7);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			UnityEngine.Vector3Int arg0 = ToLua.ToVector3Int(L, 2);
			UnityEngine.Tilemaps.TileBase arg1 = (UnityEngine.Tilemaps.TileBase)ToLua.CheckObject<UnityEngine.Tilemaps.TileBase>(L, 3);
			int arg2 = (int)LuaDLL.luaL_checknumber(L, 4);
			int arg3 = (int)LuaDLL.luaL_checknumber(L, 5);
			int arg4 = (int)LuaDLL.luaL_checknumber(L, 6);
			int arg5 = (int)LuaDLL.luaL_checknumber(L, 7);
			obj.BoxFill(arg0, arg1, arg2, arg3, arg4, arg5);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int InsertCells(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 3)
			{
				UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
				UnityEngine.Vector3Int arg0 = ToLua.ToVector3Int(L, 2);
				UnityEngine.Vector3Int arg1 = ToLua.ToVector3Int(L, 3);
				obj.InsertCells(arg0, arg1);
				return 0;
			}
			else if (count == 5)
			{
				UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
				UnityEngine.Vector3Int arg0 = ToLua.ToVector3Int(L, 2);
				int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
				int arg2 = (int)LuaDLL.luaL_checknumber(L, 4);
				int arg3 = (int)LuaDLL.luaL_checknumber(L, 5);
				obj.InsertCells(arg0, arg1, arg2, arg3);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: UnityEngine.Tilemaps.Tilemap.InsertCells");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DeleteCells(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 3)
			{
				UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
				UnityEngine.Vector3Int arg0 = ToLua.ToVector3Int(L, 2);
				UnityEngine.Vector3Int arg1 = ToLua.ToVector3Int(L, 3);
				obj.DeleteCells(arg0, arg1);
				return 0;
			}
			else if (count == 5)
			{
				UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
				UnityEngine.Vector3Int arg0 = ToLua.ToVector3Int(L, 2);
				int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
				int arg2 = (int)LuaDLL.luaL_checknumber(L, 4);
				int arg3 = (int)LuaDLL.luaL_checknumber(L, 5);
				obj.DeleteCells(arg0, arg1, arg2, arg3);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: UnityEngine.Tilemaps.Tilemap.DeleteCells");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ClearAllTiles(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			obj.ClearAllTiles();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ResizeBounds(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			obj.ResizeBounds();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CompressBounds(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)ToLua.CheckObject(L, 1, typeof(UnityEngine.Tilemaps.Tilemap));
			obj.CompressBounds();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_layoutGrid(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)o;
			UnityEngine.Grid ret = obj.layoutGrid;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index layoutGrid on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_cellBounds(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)o;
			UnityEngine.BoundsInt ret = obj.cellBounds;
			ToLua.PushValue(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index cellBounds on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_localBounds(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)o;
			UnityEngine.Bounds ret = obj.localBounds;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index localBounds on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_animationFrameRate(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)o;
			float ret = obj.animationFrameRate;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index animationFrameRate on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_color(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)o;
			UnityEngine.Color ret = obj.color;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index color on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_origin(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)o;
			UnityEngine.Vector3Int ret = obj.origin;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index origin on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_size(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)o;
			UnityEngine.Vector3Int ret = obj.size;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index size on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_tileAnchor(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)o;
			UnityEngine.Vector3 ret = obj.tileAnchor;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index tileAnchor on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_orientation(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)o;
			UnityEngine.Tilemaps.Tilemap.Orientation ret = obj.orientation;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index orientation on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_orientationMatrix(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)o;
			UnityEngine.Matrix4x4 ret = obj.orientationMatrix;
			ToLua.PushValue(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index orientationMatrix on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_tilemapPositionsChanged(IntPtr L)
	{
		ToLua.Push(L, new EventObject(typeof(System.Action<UnityEngine.Tilemaps.Tilemap,Unity.Collections.NativeArray<UnityEngine.Vector3Int>>)));
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_animationFrameRate(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.animationFrameRate = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index animationFrameRate on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_color(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)o;
			UnityEngine.Color arg0 = ToLua.ToColor(L, 2);
			obj.color = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index color on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_origin(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)o;
			UnityEngine.Vector3Int arg0 = ToLua.ToVector3Int(L, 2);
			obj.origin = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index origin on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_size(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)o;
			UnityEngine.Vector3Int arg0 = ToLua.ToVector3Int(L, 2);
			obj.size = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index size on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_tileAnchor(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)o;
			UnityEngine.Vector3 arg0 = ToLua.ToVector3(L, 2);
			obj.tileAnchor = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index tileAnchor on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_orientation(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)o;
			UnityEngine.Tilemaps.Tilemap.Orientation arg0 = (UnityEngine.Tilemaps.Tilemap.Orientation)ToLua.CheckObject(L, 2, typeof(UnityEngine.Tilemaps.Tilemap.Orientation));
			obj.orientation = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index orientation on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_orientationMatrix(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Tilemaps.Tilemap obj = (UnityEngine.Tilemaps.Tilemap)o;
			UnityEngine.Matrix4x4 arg0 = StackTraits<UnityEngine.Matrix4x4>.Check(L, 2);
			obj.orientationMatrix = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index orientationMatrix on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_tilemapPositionsChanged(IntPtr L)
	{
		try
		{
			EventObject arg0 = null;

			if (LuaDLL.lua_isuserdata(L, 2) != 0)
			{
				arg0 = (EventObject)ToLua.ToObject(L, 2);
			}
			else
			{
				return LuaDLL.luaL_throw(L, "The event 'UnityEngine.Tilemaps.Tilemap.tilemapPositionsChanged' can only appear on the left hand side of += or -= when used outside of the type 'UnityEngine.Tilemaps.Tilemap'");
			}

			if (arg0.op == EventOp.Add)
			{
				System.Action<UnityEngine.Tilemaps.Tilemap,Unity.Collections.NativeArray<UnityEngine.Vector3Int>> ev = (System.Action<UnityEngine.Tilemaps.Tilemap,Unity.Collections.NativeArray<UnityEngine.Vector3Int>>)arg0.func;
				UnityEngine.Tilemaps.Tilemap.tilemapPositionsChanged += ev;
			}
			else if (arg0.op == EventOp.Sub)
			{
				System.Action<UnityEngine.Tilemaps.Tilemap,Unity.Collections.NativeArray<UnityEngine.Vector3Int>> ev = (System.Action<UnityEngine.Tilemaps.Tilemap,Unity.Collections.NativeArray<UnityEngine.Vector3Int>>)arg0.func;
				UnityEngine.Tilemaps.Tilemap.tilemapPositionsChanged -= ev;
			}

			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

