//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_SimulationModeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.SimulationMode),"SimulationMode");
		L.RegVar("FixedUpdate", get_FixedUpdate, null);
		L.RegVar("Update", get_Update, null);
		L.RegVar("Script", get_Script, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<UnityEngine.SimulationMode>.Check = CheckType;
		StackTraits<UnityEngine.SimulationMode>.Push = Push;
	}

	static void Push(IntPtr L, UnityEngine.SimulationMode arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(UnityEngine.SimulationMode), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_FixedUpdate(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.SimulationMode.FixedUpdate);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Update(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.SimulationMode.Update);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Script(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.SimulationMode.Script);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.SimulationMode o = (UnityEngine.SimulationMode)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

